Times = ("Palmeiras", "Atlético-MG", "Fortaleza", "Bragantino", "Flamengo", "Athletico-PR", "Ceará", "Santos", "Atlético-GO", "Bahia", "Corinthians", "Fluminense", "Juventude", "Internacional", "Sport", "Cuiabá", "São Paulo", "América-MG", "Grêmio", "Chapecoense")
print("="*50)
print(Times[:5])
print("="*50)
print(Times [-4:])
print("="*50)
print(sorted(Times))
print("="*50)
print(Times.index("América-MG") + 1 )
print("="*50)
